### ISSUE TITLE
vFeed database building tools

### ISSUE THREAD

**Issue by sitsofe** [toolswatch/vFeed#40]
At the moment the excellent vFeed queries information from an sqlite database that is updated periodically but there are no tools for constructing the database from scratch.

This means that if the database provider takes a holiday/goes rogue/loses interest the information provided by vFeed becomes stale/misleading/stranded. Additionally it would allow users to have a quicker database update period if they have the resources to do so...

**Comment by rtkbkish** [comment]
I agree. This is the one thing that holds me back from using this project.

**Comment by R4v3nH0lm** [comment]
Seconded. I would love to use this but unfortunately the cve's to be updated within 24 hours to meet my needs.

**Comment by toolswatch** [comment]
Unfortunately, the update frequency is 15 days and sometimes more. I cant afford an infrastructure for doing this. I'm just a freelancer :(

**Comment by sitsofe** [comment]
NJ:
I just want to say the issue was (originally) asking if it was possible to have the source to tools used to build the database so people who wanted anything more than you were (graciously) already providing would have to build the database from scratch entirely themselves from originally sources rather download any part of it from you. I wasn't asking you to update the database more frequently (although I can see how it would appear like that) - and I apologise if it looked that way.

I suspect your answer wlil be just the same but it might be nice to clarify things :-) Thanks for your work!

**Comment by rtkbkish** [comment]
I agree. Helping with the backend ingestion tools (or infrastructure) may be a way that I or others can help.
