### ISSUE TITLE
Core vFeed code

### ISSUE THREAD

**Issue by etenjeh** [toolswatch/vFeed#44]
Hi Nabil,

I wish to know if the core vFeed source code will be available soon.

Thanks

Ambrose

**Comment by toolswatch** [comment]
for now there is no concrete decision to open the vFeed Core source. This decision is driven by many reasons I will explain very shortly.

**Comment by etenjeh** [comment]
It is rather unfortunate that it will not be open. If I build my tool just on the vFeed database, it will invite a lot of questions such as the frequency of the database update and also the warranty that it will be always maintained. I will sure have to reinvent the wheel if I wish to continue with the tool design and subsequent research
