### ISSUE TITLE
Link to english version of scip URL

### ISSUE THREAD

**Issue by tunkaflux** [toolswatch/vFeed#48]
Hi,

I asked this via Twitter as well, but is it possible to provide a link to the english version of the scip.ch page? So instead of returning for instance "http://www.scip.ch/?vuldb.77094" return "http://www.scip.ch/en/?vuldb.77094". Or make it a preference or something?

Thanks!

**Comment by toolswatch** [comment]
I got it.
In fact, i hardcode the link in my previous version and forgot to update the constants.py.
I will fix it very soon.

Thanks for reporting it and sorry for this mishap :)

regards

nj/

**Comment by toolswatch** [comment]
Fixed. The new db comes with the fixed link to english version (ex.http://www.scip.ch/en/?vuldb.12819)
