### ISSUE TITLE
Update throws connection error.

### ISSUE THREAD

**Issue by rtangxps9** [toolswatch/vFeed#50]
When executing "vfeedcli.py -u" and it is checking for latest vFeed database, it throws "Not Found" connection error. It can't get to http://www.toolswatch.org/vfeed/update.dat.

**Comment by toolswatch** [comment]
I have just reviewed and reproduced the error. The hosting did something so the .dat could not be reached.  i renamed the file update and it words. 
Temporary fix  -  Go to config/constants.py and rename update.dat to update . It should work

**Comment by toolswatch** [comment]
The vfeed api has been updated to reflect the change.  Thanks very much rtangxps9 for detecting this. It is weird that the Hosting does not accept anymore .dat file !!!
