### ISSUE TITLE
Can I separate vFeed.db and client into two hosts?

### ISSUE THREAD

**Issue by westlifezs** [toolswatch/vFeed#51]
Like the title mentioned, I want to host a local version of vFeed.db. In the meanwhile, many of instances will install just a vfeed client. These clients will periodically query the local vFeed.db on another host. My local version of vFeed.db will be updated periodically through a cron job. Could you give me some suggestions regarding the setup steps for vfeed? It seems like current vfeed.db and vfeed client can not be separated into different hosts.

Thanks,

Su Zhang

**Comment by toolswatch** [comment]
Hi Su;

As for now, the vFeed is only relying on local vfeed.db. This feature will be enabled very soon through Web API ;)
