### ISSUE TITLE
--update stops at 12%

### ISSUE THREAD

**Issue by geek4unix** [toolswatch/vFeed#56]
$ python vfeedcli.py -u
[+] Checking connectivity to http://www.toolswatch.org/vfeed/
[+] New install. Downloading the Correlated Vulnerability Database.
[+] Receiving 5709824 out of 47720679 Bytes of vfeed.db.tgz ( 12 %)

Seems to stop at 12% , retried a few times and in 3 attempts has not got past 12%

Using Mac OSX 10.11.3

Also tried on CentOS 6.7:

[root@localhost vFeed]# python vfeedcli.py --update
[+] Checking connectivity to http://www.toolswatch.org/vfeed/
[+] New install. Downloading the Correlated Vulnerability Database.
[+] Receiving 5701632 out of 47720679 Bytes of vfeed.db.tgz

**Comment by toolswatch** [comment]
I did the test again. And it works just fine !!!
Maybe you dont have the latest version of the Python API
Try a git pull 
and the  retry to update

Let me know

NJ/

**Comment by geek4unix** [comment]
I've tried again from home on the home mac and it works fine. Same version of python etc
I can only think it is related to connectivity i was using at work . Sorry for bothering you about it and thanks for your hard work :)

$ python vfeedcli.py --update
[+] Checking connectivity to http://www.toolswatch.org/vfeed/
[+] New install. Downloading the Correlated Vulnerability Database.
[+] Receiving 47720679 out of 47720679 Bytes of vfeed.db.tgz (100 %)
[+] Installing vfeed.db.tgz ...
[+] Cleaning compressed database and update file
