### ISSUE TITLE
There is not travis.yml file

### ISSUE THREAD

**Issue by UShan89** [toolswatch/vFeed#58]
At this point of time, I do not see the travis.yml file.

**Comment by UShan89** [comment]
#57 Travis build fails as there is not *.yml file for building

**Comment by toolswatch** [comment]
Hi Ushan89;
Man, i loved the Migration Scripts to MongoDB
I just turned your scripts into a class .. and i modify slightly your code to use config.py instead of hardecoded directories. Now it is easy to migrate using ./vfeedcli --migration

> show dbs
admin	(empty)
local	0.078125GB
vfeed	0.453125GB
I will publish it tomorrow with documentation (+ hacks to install brew under OSX Yosemite )

You will be credited for this great job !!

Thanks again bro

**Comment by UShan89** [comment]
@toolswatch thank you for the feedback. I just love using vfeed. 

Here is one more thing that may be of interest. 
https://github.com/UShan89/ape/blob/master/vfeedModel.py 

This is an ORM based approach to make search more simpler and avoid `select * from ?` 
I will do a pull request when I am ready. You guys are awesome for maintaining vFeed. Thank you for the changes to the script and the --migration option.

**Comment by toolswatch** [comment]
The packaging before submitting the 0.6.5 API version went well with the
integration of migration feature until I had an issue while populating the
Mongo DB one of the csv (openvas) has some UTF-8 issue. MongoDB raised an
error about UTF-8 ... have you got this while generating the vFeed mongo db
???

**Comment by UShan89** [comment]
I just tried again, map_cve_openvas is now in mongo (Testing on Windows 10 x64).

**Comment by UShan89** [comment]
Here is something interesting I found though with iconv.

http://johanndutoit.net/mongodb-import-error-utf8-unexpected-error/ 
http://www.fileformat.info/tip/linux/iconv.htm

**Comment by UShan89** [comment]
I just tested on Linux x64 (Elementary OS Freya). I could not get the UTF-8 Error.

**Comment by toolswatch** [comment]
Here is what i got

Sun Apr 10 17:08:39.004         Progress: 1625769/12064960    13%
Sun Apr 10 17:08:39.004             13000    4333/second
Sun Apr 10 17:08:42.008         Progress: 4894511/12064960    40%
Sun Apr 10 17:08:42.008             35700    5950/second
Sun Apr 10 17:08:44.336 exception:Invalid UTF8 character detected
Sun Apr 10 17:08:44.336
Sun Apr 10 17:08:45.006         Progress: 8473044/12064960    70%
Sun Apr 10 17:08:45.006             61399    6822/second
Sun Apr 10 17:08:48.008         Progress: 11467763/12064960    95%
Sun Apr 10 17:08:48.008             84499    7041/second
Sun Apr 10 17:08:48.685 check 9 89795
Sun Apr 10 17:08:48.783 imported 89794 objects
Sun Apr 10 17:08:48.783 ERROR: encountered 1 error(s)

only 1 object not imported !!

In fact i found the iconv solution, but i did not want to add a function
into the code to sanitize the csv. I want to check what entry is not
compliant.

**Comment by UShan89** [comment]
[map_cve_openvas.zip](https://github.com/toolswatch/vFeed/files/211826/map_cve_openvas.zip)

Here is my CSV.

**Comment by toolswatch** [comment]
.travis.yml added with release 0.6.5. Thanks to Ushan89

**Comment by toolswatch** [comment]
Hi Sai

I tried with your csv. Here is my output

processing .. map_cve_openvas_ushan
connected to: localhost:27017
Fri Apr 22 17:35:52.002         Progress: 1767982/12099384    14%
Fri Apr 22 17:35:52.002             14200    4733/second
Fri Apr 22 17:35:55.012         Progress: 4917527/12099384    40%
Fri Apr 22 17:35:55.012             35700    5950/second
*Fri Apr 22 17:35:57.821 exception:Invalid UTF8 character detected*
Fri Apr 22 17:35:57.822
Fri Apr 22 17:35:58.023         Progress: 7693718/12099384    63%
Fri Apr 22 17:35:58.024             55499    6166/second
Fri Apr 22 17:36:01.013         Progress: 10241221/12099384    84%
Fri Apr 22 17:36:01.013             74999    6249/second
Fri Apr 22 17:36:03.169 check 9 90041
Fri Apr 22 17:36:03.170 imported 90040 objects
Fri Apr 22 17:36:03.170 ERROR: encountered 1 error(s)

To be honest, i cant figure out. But still the CSV is imported  !!

**Comment by UShan89** [comment]
That's interesting. CSV is not the only way to export, it just was a faster option. I am going to check for alternatives and in finding solution for this error.
