### ISSUE TITLE
vFeed keeps asking to accept license

### ISSUE THREAD

**Issue by edwardmp** [toolswatch/vFeed#61]
Hi @toolswatch ,

Thanks for publishing this useful tool. I encounter a small issue.

vFeed keeps asking me to accept the license over and over:
>  ########################################### 
>  !!! Please Read Carefully the License  !!! 
>  ########################################### 

How can I accept this once so I can run the update command in a cron job (`python vfeedcli.py --update`)?

**Comment by elnappo** [comment]
At the moment it is not possible to skip this in vfeedcli.py. As a workaround you could do `echo yes | python vfeedcli.py --update`

**Comment by toolswatch** [comment]
try this 
vfeed/vfeedcli.py -u <<EOV
yes
EOV

**Comment by edwardmp** [comment]
@elnappo @toolswatch 

Thanks so much for you replies. The workaround suggested by @elnappo worked great, although I have no doubt the second would have achieved the same.
