### ISSUE TITLE
OVAL repository now hosted by CIS

### ISSUE THREAD

**Issue by fastfire** [toolswatch/vFeed#67]
When try to open urls returned by get_oval method (for example: http://oval.mitre.org/repository/?id=oval:org.mitre.oval:def:6093), Mitre page show this notice:

The official OVAL Repository is now hosted by CIS. Other OVAL content continues to be available through the "Other Repositories of OVAL Content" listed below.

**Comment by toolswatch** [comment]
Thanks .. .Fixed. It will be available very soon in the next API update.

 ---- FIX 
Modify this line in config.py
oval_url = "https://oval.cisecurity.org/repository/search/definition/"
