### ISSUE TITLE
mongo export on ubuntu is not working

### ISSUE THREAD

**Issue by n0needt0** [toolswatch/vFeed#72]
the ps command should be 
output = subprocess.Popen(["ps", "awx"], stdout=subprocess.PIPE)

in +++++++++++++++++++

def mongo_server():
    """ check whether the MongoDB is up and running
    :return: listing of processes
    """
    output = subprocess.Popen(["ps", "A"], stdout=subprocess.PIPE)
    for x in output.stdout:
        if "mongod" in x:
            return True
    return "[!] MongoDB is not running. Start the mongod service"

**Comment by toolswatch** [comment]
I got it

vakarus@core:~/vFeed/test/vFeed$ sudo ./vfeedcli.py --migrate
error: unsupported option (BSD syntax)

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.

For more details see ps(1).
[!] MongoDB is not running. Start the mongod service

I will fix it.

**Comment by toolswatch** [comment]
Git pull . New version 7.0.1 was pushed. 
Added support to Linux and OSX
