### ISSUE TITLE
vfeed community database update

### ISSUE THREAD

**Issue by Hankhh** [toolswatch/vFeed#76]
Hi Guys,

I faced with following error;

01:~/vFeed# python vfeedcli.py --update
 +++ Consultancy / Integrator Plans +++)
Please insert your private links as described in the documentation.

 +++ Community Edition Users +++
The vFeed CE must be downloaded from the official repository at https://vfeed.io
Once retrieved, it must be decompressed into the python wrapper repository.

I copied vfeed.db into the every single directory that I found, but it didn't work! Any idea?

**Comment by toolswatch** [comment]
Hi Hankhh,

Once the database in deployed in the main directory of vFeed python wrapper. it must work.
Can you post the error message you got ?

**Comment by Hankhh** [comment]
Thank you for your prompt reply. As I mentioned above it just says vFeed should be copied into the python wrapper directory, which I did. I also tried updating vFeed on another test system and same issue.
I just returned this message;

k02:~/vFeed# ./vfeedcli.py -u
 +++ Consultancy / Integrator Plans +++)
Please insert your private links as described in the documentation.

 +++ Community Edition Users +++
The vFeed CE must be downloaded from the official repository at https://vfeed.io
Once retrieved, it must be decompressed into the python wrapper repository.

**Comment by toolswatch** [comment]
Oh i understand now.

Once the vfeed.db is deployed in the main repository of the python wrapper. You dont need vfeedcli -u anymore. This feature is only for updating the database and it is only working for licensed databases. Whenever the Community Edition is updated, you will receive an email to get the build.

Try ./test.py to see if everything is fine

Now you can start using vfeed by issuing the commands. Please check the docs https://vfeed.io/docs  

please let me know
